version: '3'

services:
  nginx:
    image: mkmsimages.azurecr.io/mkmsimages/t4-nginx:latest-waf
    container_name: t4-nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
  mkms:
    image: mkmsimages.azurecr.io/mkmsimages/mkms-service:ipr
    container_name: mkms
    restart: unless-stopped
    ports:
      - 9000:9000
